.github/workflows/go.yaml
Makefile
utils/terraform_utils_test.go

The purpose of this PR is to fix the workflow jobs that are failing. Lint is failing because of the timeout, so we are increasing it, and  tests are failing because of a bad test that is expecting some context conditions that don't exist in the workflow

fix: workflow jobs failing

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller_test.go
go.mod
pkg/util/util.go
pkg/util/util_test.go

The purpose of this PR is to trigger the reconcile loop for KopsControlPlane when any KopsMachinePool related with it are modified

feat: trigger KopsControlPlaneReconciler for changes in KopsMachinePool

---

Makefile
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller_test.go

This PR is intended to fix the wrong assumption that the subnets in the KopsMachinePool were a source of truth. Now we are using the Zone attribute from the KopsControlPlane's Subnets which are more reliable in that matter

fix: infer the subnet using KopsControlPlane instead of KopsMachinePool

---

pkg/kops/kops.go
pkg/kops/kops_test.go

The goal of this PR is to fix the behavior of the GetKopsMachinePoolsWithLabel which does not consider the label's value.

fix: get kmp function to also consider the value

---

pkg/kops/kops.go
pkg/kops/kops_test.go

This PR goal is to include the Masters' ASG case when inferring the ASG name since they have a different pattern from the other roles

fix: include Masters while infering ASG name

---

.kubernetes/manifests.yaml
Makefile
apis/controlplane/v1alpha1/kopscontrolplane_types.go
apis/infrastructure/v1alpha1/kopsawscluster_types.go
apis/infrastructure/v1alpha1/kopsmachinepool_types.go
config/crd/bases/controlplane.cluster.x-k8s.io_kopscontrolplanes.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_kopsawsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_kopsmachinepools.yaml
config/crd/output/apiextensions.k8s.io_v1_customresourcedefinition_kopsawsclusters.infrastructure.cluster.x-k8s.io.yaml
config/crd/output/apiextensions.k8s.io_v1_customresourcedefinition_kopscontrolplanes.controlplane.cluster.x-k8s.io.yaml
config/crd/output/apiextensions.k8s.io_v1_customresourcedefinition_kopsmachinepools.infrastructure.cluster.x-k8s.io.yaml
controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller_test.go

The goal of this PR to improve the usability of the pause annotation for the CRs. The idea is that when a resource in a higher hierarchy is paused then all the related resources are paused as well. In this case we decided the following hierarchy: cluster > kcp > kmp. So if a cluster object is paused, then the reconcile will also be stopped for the respective kcp and kmps. We are adding a paused status to improve the visibility of the status and also adding logs to be clear about which resource is causing it.

refactor: setup hierarchy between the pause annotations

---

controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller_test.go

This PR changes the Kops Controller behavior to not rely on the cluster name for the IG name and use the KopsMachinePool meta name for it.
Before we had an invisible pattern, if the KopsMachinePool name didn't started with the cluster name, the controller would fail.
With this PR the kops-operator acts in the same way as the other Cluster-API providers.

Use KMP name as IG name

---

.kubernetes/manifests.yaml
config/manager/kustomization.yaml
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller_test.go
main.go

This PR will fix the function to retrieve the ASG since the AWS API don't accept the usage of name and others filters

fix: remove filter from DescribeAutoScalingGroups

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
main.go

The goal of this PR is to always get the kops client between the reconciliations to avoid leak between them

fix: always get kops client to avoid leak between reconciliations

---

.github/workflows/go.yaml
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller.go
controllers/infrastructure.cluster.x-k8s.io/kopsmachinepool_controller_test.go
main.go

The goal of this PR is the same as the one before, this time is being applied in the kopsmachinepool controller as well

fix: always get kops client to avoid leak between reconciliations for kmp controller

---

controllers/controlplane/kopscontrolplane_controller.go
utils/templates/spotinst_ocean_aws_override.tf.tpl

The goal of this PR is to add ignore to some fields that we are unable to define using only the kops configurations i.e.: we don't want to changed the desired_capacity since spot should autoscale

fix: add ignore changes to spotinst_ocean_aws to some of the fields

---

go.mod
go.sum

Update kops fork version with Karpenter 0.28.1 update

chore: update karpenter to v0.28.1

---

.tool-versions
controllers/controlplane/kopscontrolplane_controller_test.go
pkg/helpers/helpers.go
utils/kops_utils.go
utils/kops_utils_test.go

Move done so we can use those same methods on other projects/packages.

feat: move functions used by some tests to a helpers packager

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go

Export function regionBySubnet

chore: export regionBySubnet

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
utils/templates/karpenter_custom_addon_boostrap.tf.tpl
utils/templates/tests/data/aws_s3_object_karpenter_provisioners_content
utils/templates/tests/karpenter_custom_addon_boostrap.tf

The goal of this PR is to configure prune for the Karpenter provisioners that are created using Kops' custom addons.The idea is that they will be removed from the remote cluster by protokube component when they are removed from the instance group configuration

feat: configure prune for karpenter addon provisioners

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go

Change the default requeue time to 1 hour

Change requeue time to 1 hours, while we don't configure with configmap to avoid AWS api quota limit

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
main.go

The problem this PR is solving is that after the event enqueues a cluster to the reconciliation loop, the cluster is always requeued, even when the controllerClass of the cluster is changed. What the reconciliation is doing now is verifying the controllerClass at the beginning of each reconciliation and stoping the requeue when needed

fix: remove objects from reconciliation queue when it's managed by a different controller class

---

go.mod

This PR purpose is to remove a unused replacement from the go.mod file

fix: remove unused replace from go.mod

---

apis/controlplane/v1alpha1/kopscontrolplane_types.go
apis/infrastructure/v1alpha1/kopsmachinepool_types.go
config/controlplane.cluster.x-k8s.io_kopscontrolplanes.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kopscontrolplanes.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_kopsmachinepools.yaml
config/crd/output/apiextensions.k8s.io_v1_customresourcedefinition_kopscontrolplanes.controlplane.cluster.x-k8s.io.yaml
config/crd/output/apiextensions.k8s.io_v1_customresourcedefinition_kopsmachinepools.infrastructure.cluster.x-k8s.io.yaml
config/infrastructure.cluster.x-k8s.io_kopsmachinepools.yaml
controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
pkg/helpers/helpers.go

The goal of this PR is to add support to remove the Kops instance groups on reflection to the deletion of the KopsMachinePool resource

feat: add support to remove instance groups on kmp deletion

---

.kubernetes/manifests.yaml
apis/controlplane/v1alpha1/kopscontrolplane_types.go
config/controlplane.cluster.x-k8s.io_kopscontrolplanes.yaml
config/crd/bases/controlplane.cluster.x-k8s.io_kopscontrolplanes.yaml
config/crd/output/apiextensions.k8s.io_v1_customresourcedefinition_kopscontrolplanes.controlplane.cluster.x-k8s.io.yaml
config/manager/kustomization.yaml
controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go

The goal of this PR is to add support to specify cluster addons in the KopsControlPlane spec following [this](https://kops.sigs.k8s.io/addon_objects/). The motivation for this is to be able to apply KubeSchedulerConfiguration to the clusters

feat: add support do cluster addon in kopscontrolplane resource

---

controllers/controlplane/kopscontrolplane_controller.go
pkg/kops/kops.go
pkg/kops/kops_test.go

The goal of this MR is to add support to calculate the serviceClusterIPRange as it was before Kops 1.28, more context can be found here: https://github.com/kubernetes/kops/pull/15866

feat: add function to calculate serviceClusterIPRange

---

controllers/controlplane/kopscontrolplane_controller.go
utils/kops_utils.go

The goal of this PTAL is to fix concurrent issues that may happen because of the order that the deletion is being made

fix: correct the order of the deletion routine

---

metrics/metrics.go

The PR is to change the tag name of the custom metric as it conflicts with the tags used by Datadog

fix: update tag name of custom metrics

---

config/manager/kustomization.yaml
controllers/controlplane/kopscontrolplane_controller_test.go
utils/fixtures/karpenter/test_successful_ec2_node_class.tpl
utils/templates/ec2nodeclass.yaml.tpl
utils/templates/tests/data/karpenter_resource_output_node_pool.yaml
utils/templates/tests/data/karpenter_resource_output_node_pool_and_provisioner.yaml

The goal of this PR is to add the KubernetesCluster tag to the NodePool template

fix: add KubernetesCluster tag to NodePool template

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
utils/fixtures/karpenter/test_successful_ec2_node_class.tpl
utils/karpenter_utils.go
utils/templates/ec2nodeclass.yaml.tpl
utils/templates/tests/data/karpenter_resource_output_node_pool.yaml
utils/templates/tests/data/karpenter_resource_output_node_pool_and_provisioner.yaml

The goal of this PR is to add support to configure the NodePool disruption.budgets, this is only possible after upgrading karpenter to +0.34 version

Add support node pool budget

---

controllers/controlplane/kopscontrolplane_controller.go
controllers/controlplane/kopscontrolplane_controller_test.go
pkg/utils/kops_utils.go

This PR enhances the logging capabilities during the cluster deletion process to improve observability and debugging. Added logging statements to track the progress of:
- Terraform destroy operations
- Kops resource deletion
- Cloud resource cleanup

chore: improve logging of cluster deletion process

---

controllers/controlplane/kopscontrolplane_controller_test.go
pkg/utils/karpenter_utils.go
pkg/utils/karpenter_utils_test.go

Fixes missing cloud labels from KopsMachinePool in generated Karpenter EC2NodeClass resources.

fix: properly retrieve cloud labels from kmp alonside with the kcp ones
